management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
            cors:
                allowed-origins: '*'
                allowed-methods: '*'
                allowed-headers: '*'
spring:
    cloud:
        stream:
            bindings:
                eventChannel-in-0:
                    destination: eventTopic
                    content-type: application/json
                notificationChannel-out-0:
                    destination: notificationTopic
                    content-type: application/json
            binders:
                rabbit:
                    environment:
                        spring:
                            rabbitmq:
                                password: guest
                                username: guest
                                port: '5672'
                                host: localhost
                    type: rabbit
            default:
                contentType: application/json
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: 'true'
        show-sql: 'true'
    application:
        name: notifications
    datasource:
        password: test123
        username: portal-notifications
        url: jdbc:postgresql://localhost:5434/portal-notifications
    jmx:
        default-domain: notifications
server:
    port: '2003'
portal-notifications:
    base-url: https://please_overwrite/
    schedule:
        cron: '0 * * * * *'

logging:
    level:
        org:
            springframework:
                integration: DEBUG
                security: DEBUG

portal.auth.keycloak-uri: http://localhost:8080
